[build-system]
requires = ["setuptools>=61.0", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "streamlit-entra"
description = "Streamlit component for Microsoft Entra ID (MSAL) authentication"
dynamic = ["version"]
authors = [
    {name = "Victor Gruselius", email="victor.gruselius@gmail.com"},
]
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "streamlit",
]

[project.urls]
homepage = "https://github.com/tingiskhan/streamlit-msal"

[tool.black]
line-length = 120

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
include = ["streamlit_entra*"]

[tool.setuptools.package-data]
streamlit_entra = [
    "frontend/build/*",
    "frontend/build/**/*",
]

[tool.setuptools_scm]
fallback_version = "0.0.0+dev"
