name: Build & Release Streamlit Component
on:
  push:
    branches:
      - master

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Get version
        id: get_version
        run: echo "version=$(grep "__version__" msal_login/__init__.py | cut -d '"' -f2)" >> $GITHUB_OUTPUT

      - name: Create tar archive
        run: make package VERSION=${{ steps.get_version.outputs.version }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: "Release v${{ steps.get_version.outputs.version }}"
          body: "Automated release"
          files: msal-login-${{ steps.get_version.outputs.version }}.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
